<?php

namespace FilmBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository {

    public function FindFilmByTitre($motcle) {
        $query = $this->createQueryBuilder('f')
                ->where('f.titre like :titre')
                ->setParameter('titre', $motcle . '%')
                ->orderBy('f.titre', 'ASC')
                ->getQuery();

        return $query->getResult();
    }

}
